---
- name: Verify connectivity to all hosts
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    # -- Show version summary for all devices --
    - name: Test connection and show version
      ios_command:
        commands: show version
      register: version_output
 
    - name: Display version summary
      debug:
        msg: "Device {{ inventory_hostname }} version: {{ version_output.stdout_lines[0][0:50] }}"
